### ISSUE TITLE
 Implementing multi-regions and support zone configuration for OpenShift clusters

### ISSUE THREAD

**Issue by sergkoudi** [InseeFrLab/onyxia#516]
Hello,
I would like to start a discussion about multi-region feature in Onyxia.

### Use case

At EDF, we have the following use case:

- We have OpenShift clusters.
- We want to make the Onyxia user to choose a region where he wants to run a service. A user can use multiple regions at the same time.
- We associate a region with a network zone. We have several network zones configured for a single OpenShift cluster. In our case, zones isolate different resources such as databases, engines etc. Running a workload (or a pod) in a zone is just running it in the specific set of k8s nodes using selectors.
- In OpenShift, configuration of a zone for workloads is propagated via the properties `metadata.annotations`  together with `metadata.labels` of its Namespace. Example:
```
kind: Namespace
apiVersion: v1
metadata:
  name: namespace-xxxxxx
  labels:
    edf.fr/environnement: hors-prod
    edf.fr/espace: groupe
  annotations:
    openshift.io/node-selector: 'edf.fr/espace=groupe,edf.fr/environnement=hors-prod'
```

### Implementation

So, to make this possible, there must be contrbutions on onyxia-api and onyxia-ui:

1. For **onyxia-ui**:

It requires switching between regions:
- when you display all your running services (page My Services)
- when you launch a new service (probably in the service configuration).

2. For **onyxia-api**:

It requires adding a few properties to  [`region[].services`](https://github.com/InseeFrLab/onyxia-api/blob/master/docs/region-configuration.md#services-properties), I propose these:

- `namespaceLabels` - array of key-value pairs
- `namespaceAnnotations` - array of key-value pairs

When a namespace is created (on user login), it is provisioned with `metadata.annotations` and `metadata.labels` properties accordingly.

### Notes

The configuration in this way of using specific zones for workloads is only implemented in OpenShift cluster, not for regular Kubernetes. However, provisioning with `metadata.annotations` and `metadata.labels` can serve for whatever else in regular clusters.
