### ISSUE TITLE
Theming: customize home page cards

### ISSUE THREAD

**Issue by mmwinther** [InseeFrLab/onyxia#570]
The cards displayed at the bottom of the home page currently contain hardcoded content. The ability to configure the text displayed here and the link targets is highly desirable. Currently, when deployed in contexts outside SSPCloud these links will confuse users by taking them to SSPCloud pages.

![Screen Shot 2023-08-01 at 12 33 05](https://github.com/InseeFrLab/onyxia-web/assets/42948872/cde52208-1fcb-4de9-9e1f-96b51306f9e7)

**Comment by phlg** [comment]
We are also really interested in this feature for our own in-house deployment of Onyxia !

**Comment by garronej** [comment]
Hey @mmwinther,  
Sure thing, let's address that,  
What do you guys want:  
- Just an option to remove that section?  
- The possibility to provide a mardown text that would be rendered as HTML on the homepage?  
- An array of `{ svgUrl: string; title: LocalizedString; description: LocalizedString; url: string }`?

**Comment by odysseu** [comment]
How about some yaml in the onyxia.values' regions like so:
```yaml
regions: [
  {
    "cards": {
      "card1": {
        svgUrl: string,
        title: LocalizedString,
        description: LocalizedString,
        url: string
      },
      "card2": {
        svgUrl: string,
        title: LocalizedString,
        description: LocalizedString,
        url: string
      },
      ...
    },
    ...
  }
]
```
each `cardx` would add a _"card"_ with the content described.

If no card in the `cards`, just render this, and maybe center the logo (which would also deserve a basic onyxia configuration field 😃) :

![image](https://github.com/InseeFrLab/onyxia/assets/55583423/65e2478a-56a7-4c74-8731-e48a38a7ea55)
