### ISSUE TITLE
Extending catalogs organization 

### ISSUE THREAD

**Issue by nitreb** [InseeFrLab/onyxia#658]
Hi,
We would like to be able to display multiple lists of catalogs in the Onyxia sidebar. The idea is to provide an extra dimension to organize our catalogs. 
In our case for example, we could have themes like "IDE" catalogs, which would include tabs like "Jupyter Notebooks", "VSCodes", etc...
![image](https://github.com/InseeFrLab/onyxia/assets/51701372/c59ee374-b0f0-4468-b2cd-388ee8418cd9)

Would it be conceivable ton enhance the `onyxia-values.yaml` keys to allow such a feature? It is just an idea tho, maybe you already have something better in mind.

**Comment by odysseu** [comment]
You need to be in the onyxia chart v7. (see [how to migrate from version 6 to version 7](https://docs.onyxia.sh/migration-guides/v6-greater-than-v7))

You would have as currently available in your `onyxia.values` something like this : 
```yaml
onyxia:
  web: ...
  api:
    region: ...
    catalogs:
      [
        {
          "id": "ide",
          "name": "Interactive services",
          "description": "IDE for datascientists.",
          "location": "https://inseefrlab.github.io/helm-charts-interactive-services",
          "status": "PROD",
          "highlightedCharts":
            [
              "jupyter-python",
              "rstudio",
              ...
              "vscode-tensorflow",
            ],
          "type": "helm",
        },
        {
          "id": "databases",
          "name": "Databases",
          "description": "Databases services.",
          "location": "https://inseefrlab.github.io/helm-charts-databases",
          "status": "PROD",
          "highlightedCharts":
            [
              "postgresql",
              "elastic",
              ...
              "metabase",
            ],
          "type": "helm",
        },
        {
          "id": "inseefrlab-helm-charts-datascience",
          "name": "Deprecated",
          "description": "Services for datascientists.",
          "location": "https://inseefrlab.github.io/helm-charts-datascience",
          "status": "PROD",
          "highlightedCharts": ["ubuntu", "openrefine"],
          "excludedCharts":
            [
              "rstudio",
              "jupyter",
              ...
              "delta-sharing-server",
            ],
          "type": "helm",
        },
        {
          "id": "automation",
          "name": "Automation",
          "description": "AIOps & MLOps services.",
          "location": "https://inseefrlab.github.io/helm-charts-automation",
          "status": "PROD",
          "highlightedCharts":
            ["argo-workflows", "mlflow", "metaflow", "argo-cd", "label-studio"],
          "type": "helm",
        },
        {
          "id": "divers",
          "name": "Experimental",
          "description": "Services divers.",
          "location": "https://inseefrlab.github.io/helm-charts-miscellaneous",
          "status": "PROD",
          "type": "helm",
        },
       ...
     ]
```
which renders like so : ![image](https://github.com/InseeFrLab/onyxia/assets/55583423/18c41fdb-135f-4497-8842-61a0a7144d6e)

Then you can use the `LEFTBAR_LINK` like in this doc : https://github.com/InseeFrLab/onyxia/blob/v7.0.0/web/.env#L309-L316

To use it like so:

```yaml
onyxia:
  web:
    ...,
    HEADER_LINKS: |
     [
       {
         "label": "IDE"
         "icon": "https://.../someLogo.png", 
         "url": "/catalog/ide" 
       },
       {
         "label": "automation"
         "icon": "https://.../someLogo2.png", 
         "url": "/catalog/automation" 
       },
       {
         "label": "other charts"
         "icon": "https://.../someLogo3.png", 
         "url": "/catalog/others" 
       },
 ]
  api: ...
```
and have it render something like :

<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/6702424/282921886-fbadc4f0-dd4c-4eef-9087-29624e7cb632.png" width="300">

Then you can have each link point to a given catalog. 

Bonus: you can always use the `"status": "DEV",` in this `api:catalogs: ...` to hide the catalog in the "Catalogs page"'s tabs, and only have them in your left vertical bar.
