### ISSUE TITLE
Can't add images because of Cross-Origin Resource Sharing (CORS) missing Access-Control-Allow-Origin 

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#659]
Hi,
I am trying to customize our Onyxia instance and I am having troubles putting some images that are in our gitlab instance : 

![image](https://github.com/InseeFrLab/onyxia/assets/55583423/869a9c82-25b1-4730-8c8c-11af88e96b64)

It seems the problem is Cross-Origin Resource Sharing (CORS) missing Access-Control-Allow-Origin : https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin
I thought I could add something like:

```yaml
onyxia:
    web:
        ...,
        env:
          HTML_HEAD: |
            <meta>
              Access-Control-Allow-Origin: https://gitlab.myinstance.fr;
            </meta>
```

in the section made for this (from what I understand) : https://github.com/InseeFrLab/onyxia/blob/v7.1.1/web/.env#L556-L581

But I am struggling. Any help please ?

thanks

**Comment by garronej** [comment]
Yes, sorry!  
I'm currently producing a video tutorial and testing thing through and through.  
I'm hype to see that you have already started trying to customise your instance but will you wait until monday? You'll have a much better experience.  

Regarding your problem. The recommended approach for customizing an onyxia instance is to host your custom resources directly within your onyxia instance. This is not documented enought but I'm working on it!  

![image](https://github.com/InseeFrLab/onyxia/assets/6702424/f8045e5d-69d9-4ce9-b73d-f89700feed48)

**Comment by odysseu** [comment]
We're having trouble using `CUSTOM_RESSOURCES `as cited in https://3innovation.slack.com/archives/C01AG3KTY8Z/p1700549810712259.
There is an artifact in a gitlab project's artifacts built using `.gitlab-ci.yml`:
```yml
build:
  artifacts:
    paths:
      - "onyxia-myenterprise-resources.zip"
```

and the onyxia.values is like so :
```yml
onyxia:
  web:
    env:
      CUSTOM_RESOURCES: "https://gitlab.insee.fr/path_to_icons/-/jobs/artifacts/main/download?job=build"
      HEADER_LOGO: "%PUBLIC_URL%/onyxia-myenterprise-resources/icons_svg/logo.svg"
```
Yet we stille have the problem `Access-Control-Allow-Origin missing`
