### ISSUE TITLE
Improve handling of "onyxia metadatas"

### ISSUE THREAD

**Issue by ihiverlet** [InseeFrLab/onyxia#795]
Hi ! 

As of today, when launching a service, Onyxia metadatas (such as the friendly name of a service) are stored in values.yaml files.

A cleaner way to handle such metadata would be to create a secret with all relevant information. This secret could be created ad hoc thanks to the API and be attached to the right helm release via the owner reference.

Not only this could allow us to have a better handling of metadata but the secret would also be deleted when doing an `helm uninstall`. 

An example of such a secret : 

```
apiVersion: v1
kind: Secret
metadata:
  name: onyxia-metadata-[release-name]
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Secret
    name: [helm release secret name]
    uid: [helm-release-uid]
data:
  friendlyName: "service-friendly-name"
```
