### ISSUE TITLE
Accessing user groups from OIDC to Apply a Node Selector

### ISSUE THREAD

**Issue by rbourgeat** [InseeFrLab/onyxia#926]
Hi ! According to the [Onyxia documentation](https://docs.onyxia.sh/docs.onyxia.sh/v8/admin-doc/catalog-of-services), in the Onyxia Content section, the user object contains a groups property extracted from the OIDC token:

```yaml
user: {
        idep: string;
        name: string;
        email: string;
        password: string;
        ip: string;
        darkMode: boolean;
        lang: "en" | "fr" | "zh-CN" | "no" | "fi" | "nl" | "it" | "es" | "de";
        /**
         * Decoded JWT OIDC ID token of the user launching the service.
         *
         * Sample value:
         * {
         *   "sub": "9000ffa3-5fb8-45b5-88e4-e2e869ba3cfa",
         *   "name": "Joseph Garrone",
         *   "aud": ["onyxia", "minio-datanode"],
         *   "groups": [
         *       "USER_ONYXIA",
         *       "codegouv",
         *       "onyxia",
         *       "sspcloud-admin",
         *   ],
         *   "preferred_username": "jgarrone",
         *   "given_name": "Joseph",
         *   "locale": "en",
         *   "family_name": "Garrone",
         *   "email": "joseph.garrone@insee.fr",
         *   "policy": "stsonly",
         *   "typ": "ID",
         *   "azp": "onyxia",
         *   "email_verified": true,
         *   "realm_access": {
         *       "roles": ["offline_access", "uma_authorization", "default-roles-sspcloud"]
         *   }
         * }
         */
        decodedIdToken: Record<string, unknown>;
    };
```

I don't know if it is possible, but i would like to know how to retrieve this information (user.groups) in my context in order to apply a Node Selector based on the user’s group.

Something like that:

```yaml
{
  "type": "object",
  "properties": {
    "nodeSelector": {
      "type": "object",
      "properties": {
        "kubernetes.io/hostname": {
          "type": "string",
          "default": "",
          "x-onyxia": {
            "overwriteDefaultWith": "{{#eq user.groups 'test'}}test-node-1,test-node-2,test-node-3{{/eq}}"
          }
        }
      }
    }
  }
}
```

Thanks in advance for your help!
