### ISSUE TITLE
Feature : Fall back on values.yaml when when overwriteDefaultWith misses values to be fully templated

### ISSUE THREAD

**Issue by ihiverlet** [InseeFrLab/onyxia#975]
Hello,

Within `values.schema.json`, would it be possible to fall back on a default value when a value is missing ?

For example, in the following extract from `values.schema.json`: when `{{git.email}}` is missing, is it possible to use a default value - either specified in `values.yaml` or defined directly within `values.schema.json` ? Ideally, I would like to have a fallback mechanism in place for missing values, provided implementing such a feature isn't too complex or resource-intensive.

```json
                "overwriteDefaultWith": [
                  {
                    "name": "LANGFUSE_INIT_ORG_ID",
                    "value": "onyxia"
                  },
                  {
                    "name": "LANGFUSE_INIT_USER_EMAIL",
                    "value": "{{ git.email }}"
                  }
```
Corresponding `values.yaml`
```yaml
    additionalEnv:
      - name: "LANGFUSE_INIT_ORG_ID"
        value: "onyxia"
      - name: "LANGFUSE_INIT_USER_EMAIL"
        value: "test@test.com"
```

Expected result when `git.email` is missing : 
```yaml
      - name: "LANGFUSE_INIT_ORG_ID"
        value: "onyxia"
      - name: "LANGFUSE_INIT_USER_EMAIL"
        value: "test@test.com"
```

Actual behavior when `git.email` is missing : 
```yaml
      - name: "LANGFUSE_INIT_ORG_ID"
        value: "onyxia"
      - name: "LANGFUSE_INIT_USER_EMAIL"
        value: ""
```

**Comment by fcomte** [comment]
why using git and not user.email?

**Comment by garronej** [comment]
That makes perfect sens to me and this is how it should work.

**Comment by ihiverlet** [comment]
> why using git and not user.email?

Sure, better than git.email but it will be empty in group namespaces no ?

**Comment by garronej** [comment]
I'm implementing it now since this is an easy clap.

**Comment by ihiverlet** [comment]
Thank you !

**Comment by garronej** [comment]
Sorry @ihiverlet, I might have been a bit *hoptimistic* 😅.

Implementing this for a specific case isn't technically difficult, but after discussing it with @fcomte, we agreed that the behavior would feel a bit too "magical" — the fallback rule wouldn't be clear or predictable.

A more readable approach could be to **fall back to the full default if *any* of the values in the object fail to resolve**. Would that work for your use case?

Something like:

```json
"overwriteDefaultWith": [
  {
    "name": "LANGFUSE_INIT_ORG_ID",
    "value": "!!!!!!!!!!!!!onyxia specific!!!!!!!!!!!!!!!!"
  },
  {
    "name": "LANGFUSE_INIT_USER_EMAIL",
    "value": "{{ git.email }}"
  }
]
```

Corresponding `values.yaml`:

```yaml
additionalEnv:
  - name: "LANGFUSE_INIT_ORG_ID"
    value: "onyxia"
  - name: "LANGFUSE_INIT_USER_EMAIL"
    value: "test@test.com"
```

**Expected result** (when `git.email` is missing — we fall back to the whole default array):

```yaml
- name: "LANGFUSE_INIT_ORG_ID"
  value: "onyxia"
- name: "LANGFUSE_INIT_USER_EMAIL"
  value: "test@test.com"
```

Let me know if that fallback logic would suit your needs.
