### ISSUE TITLE
overwriteDefaultWith for object and array.

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#992]
When we have an overwriteDefaultWith at array level , we need an exact match between the content of the object inside the onyxia context and the schema of the item. 

But obviously some charts may want to restrict the number of attributes to use : 

Onyxia should : 

- [x] be able to use a partial object declared in the chart. 
- [x] be able to remap field based on the overwriteDefaultwith syntaxe and accept relative path 

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "x-onyxia": {
    "overwriteDefaultWith": "{{user.profile.s3Profiles}}"
  },
  "items": {
    "type": "object",
    "properties": {
      "host": { "type": "string" , "default": "", "x-onyxia": {"overwriteDefaultWith": "{{endpoint}}" }},
      "accessKeyId": { "type": "string", "default": "", "x-onyxia": {"overwriteDefaultWith": "{{accessKeyId}}" }},
      "secretAccessKey": { "type": "string", "default": "", "x-onyxia": {"overwriteDefaultWith": "{{secretAccessKey}}" }},
    }
  }
}
```

```yaml
profileSchema: |
  {
    "type": "object",
    "properties": {
      "s3Profiles": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "endpoint": { "type": "string", "default": "" },
            "accessKeyId": { "type": "string", "default": ""},
            "secretAccessKey": { "type": "string", "default": "" },
            "region": { "type": "string", "default": ""}
          }
        }
      }
   }
```
This schema must work even if instance of user.profile.s3Profiles contain for example additionnal region string 
But also support the fact the field host must take value from the endpoint parameter.
